eureka:
  instance:
    prefer-ip-address: true
spring:
  profiles:
    active: default
  application:
    name: CONFIG-DEV
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
